name: 'analytics_transformation'
version: '1.0.0'
config-version: 2

profile: 'analytics_dw'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  analytics_transformation:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
